In [1]:
!pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
!pip install --upgrade scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [10]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.0.2'

In [13]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'colour': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0 , 89.0, 99.0, 129.0, 79.0],
    'weigh': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}
df_raw = pd.DataFrame(data=data)
df_raw


size colour  gender  price  weigh bought
0   XL    red  female  199.0    500    yes
1    L  green    male   89.0    450     no
2    M   blue    male   99.0    300    yes
3    L  green  female  129.0    380     no
4    M    red  female   79.0    410    yes

In [14]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   colour  5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weigh   5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [15]:
for col in ['size', 'colour', 'gender', 'bought']:
  df[col] = df[col].astype('category')

df['weigh'] = df['weigh'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   colour  5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weigh   5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


In [17]:
df.describe()

price       weigh
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [18]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price    5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weigh    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [19]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
colour     5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [20]:
df

size colour  gender  price  weigh bought
0   XL    red  female  199.0  500.0    yes
1    L  green    male   89.0  450.0     no
2    M   blue    male   99.0  300.0    yes
3    L  green  female  129.0  380.0     no
4    M    red  female   79.0  410.0    yes

In [21]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [22]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [23]:
le.classes_

array(['no', 'yes'], dtype=object)

In [26]:
df['bought'] = le.fit_transform(df['bought'])
df

size colour  gender  price  weigh  bought
0   XL    red  female  199.0  500.0       1
1    L  green    male   89.0  450.0       0
2    M   blue    male   99.0  300.0       1
3    L  green  female  129.0  380.0       0
4    M    red  female   79.0  410.0       1

In [27]:
le.inverse_transform(df['bought'])

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [28]:
df['bought'] = le.inverse_transform(df['bought'])
df

size colour  gender  price  weigh bought
0   XL    red  female  199.0  500.0    yes
1    L  green    male   89.0  450.0     no
2    M   blue    male   99.0  300.0    yes
3    L  green  female  129.0  380.0     no
4    M    red  female   79.0  410.0    yes

In [30]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse=False)

In [31]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [32]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [33]:
encoder = OneHotEncoder(drop='first', sparse=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [34]:
df


size colour  gender  price  weigh bought
0   XL    red  female  199.0  500.0    yes
1    L  green    male   89.0  450.0     no
2    M   blue    male   99.0  300.0    yes
3    L  green  female  129.0  380.0     no
4    M    red  female   79.0  410.0    yes

In [35]:
pd.get_dummies(data=df)

price  weigh  size_L  size_M  size_XL  colour_blue  colour_green  \
0  199.0  500.0       0       0        1            0             0   
1   89.0  450.0       1       0        0            0             1   
2   99.0  300.0       0       1        0            1             0   
3  129.0  380.0       1       0        0            0             1   
4   79.0  410.0       0       1        0            0             0   

   colour_red  gender_female  gender_male  bought_no  bought_yes  
0           1              1            0          0           1  
1           0              0            1          1           0  
2           0              0            1          0           1  
3           0              1            0          1           0  
4           1              1            0          0           1

In [36]:
pd.get_dummies(data=df, drop_first=True)

price  weigh  size_M  size_XL  colour_green  colour_red  gender_male  \
0  199.0  500.0       0        1             0           1            0   
1   89.0  450.0       0        0             1           0            1   
2   99.0  300.0       1        0             0           0            1   
3  129.0  380.0       0        0             1           0            0   
4   79.0  410.0       1        0             0           1            0   

   bought_yes  
0           1  
1           0  
2           1  
3           0  
4           1

In [37]:
pd.get_dummies(data=df, drop_first=True, prefix='new')

price  weigh  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0  500.0      0       1          0        1         0        1
1   89.0  450.0      0       0          1        0         1        0
2   99.0  300.0      1       0          0        0         1        1
3  129.0  380.0      0       0          1        0         0        0
4   79.0  410.0      1       0          0        1         0        1

In [38]:
pd.get_dummies(data=df, drop_first=True, prefix_sep='-')

price  weigh  size-M  size-XL  colour-green  colour-red  gender-male  \
0  199.0  500.0       0        1             0           1            0   
1   89.0  450.0       0        0             1           0            1   
2   99.0  300.0       1        0             0           0            1   
3  129.0  380.0       0        0             1           0            0   
4   79.0  410.0       1        0             0           1            0   

   bought-yes  
0           1  
1           0  
2           1  
3           0  
4           1

In [39]:
pd.get_dummies(data=df, drop_first=True, columns=['size'])

colour  gender  price  weigh bought  size_M  size_XL
0    red  female  199.0  500.0    yes       0        1
1  green    male   89.0  450.0     no       0        0
2   blue    male   99.0  300.0    yes       1        0
3  green  female  129.0  380.0     no       0        0
4    red  female   79.0  410.0    yes       1        0

Standaryzacja - StandardScaler
std() - pandas nieobciążony estymator wariancji

std() - numpy obciążony

In [41]:
print(f"{df['price']}\n")
print(f"Średnia: {df['price'].mean()}")
print(f"Odchylenie standardowe: {df['price'].std():.4f}")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia: 119.0
Odchylenie standardowe: 48.4768


In [42]:
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [44]:
def standarize(x):
  return (x - x.mean()) / x.std()

standarize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [45]:
from sklearn.preprocessing import scale 
scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [46]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [47]:
scaler = StandardScaler()
df[['price', 'weigh',]] = scaler.fit_transform(df[['price', 'weigh']])
df

size colour  gender     price     weigh bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

Przygotowanie danych do modelu 

In [48]:
df = df_raw.copy()
df

size colour  gender  price  weigh bought
0   XL    red  female  199.0    500    yes
1    L  green    male   89.0    450     no
2    M   blue    male   99.0    300    yes
3    L  green  female  129.0    380     no
4    M    red  female   79.0    410    yes

In [56]:
le = LabelEncoder()

df['bought'] = le.fit_transform(df['bought'])

scaler = StandardScaler()
df[['price', 'weigh']] = scaler.fit_transform(df[['price', 'weigh']])

df = pd.get_dummies(data=df, drop_first=True)
df


price     weigh  bought  size_M  size_XL  colour_green  colour_red  \
0  1.845062  1.366002       1       0        1             0           1   
1 -0.691898  0.623610       0       0        0             1           0   
2 -0.461266 -1.603567       1       1        0             0           0   
3  0.230633 -0.415740       0       0        0             1           0   
4 -0.922531  0.029696       1       1        0             0           1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0